
const metadata_fields = {
  league: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"name",pretty_name: "League Name", data_type: "string", pretty_key:"true"},
  ],
  college: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"name", pretty_name: "College", data_type: "string", pretty_key:true},
  ],
  nationality: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"nationality", pretty_name: "Nationality", data_type: "string", pretty_key:true},
  ],
  report_type: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"report_name", pretty_name: "Report Type", data_type: "string", pretty_key:true},
  ],
  coach: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"first_name",  pretty_name: "First Name", data_type: "string", index:true},
    {name:"last_name", order_by:"true", section:"basic", pretty_name: "Last Name", data_type: "string", index:true},
    {name:"full_name", pretty_key:true, derived:"{first_name}  {last_name}", pretty_name: "Full Name", data_type: "string"},
  ],
  conference: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"name", pretty_name: "Conference Name", data_type: "string", pretty_key:true},
  ],
  division: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"division", pretty_name: "Division", data_type: "string", pretty_key:true},
  ],
  agency: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"agency", pretty_name: "Agency Name", data_type: "string", pretty_key:"true"},
  ],
  agent: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"first_name",section:"basic",  pretty_name: "First Name", data_type: "string", index:true},
    {name:"last_name", order_by:"true", section:"basic", pretty_name: "Last Name", data_type: "string", index:true},
    {name:"full_name", pretty_key:true, derived:"{first_name}  {last_name}",  section:"basic", pretty_name: "Full Name", data_type: "string"},
    {name:"agency",  section:"basic", pretty_name: "Agency", references:"agency"},    
    {name:"email", section:"contact", pretty_name: "Email", data_type: "string"},
    {name:"phone", section:"contact", pretty_name: "Phone", data_type: "string"},
  ],
  scout: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"first_name",section:"basic",  pretty_name: "First Name", data_type: "string"},
    {name:"last_name", order_by:"true", section:"basic", pretty_name: "Last Name", data_type: "string", pretty_key:true},
    {name:"full_name", derived:"{first_name}  {last_name}",  section:"basic", pretty_name: "Full Name", data_type: "string"},
    {name:"email", order_by:"true", section:"contact", pretty_name: "Email", data_type: "string"},
    {name:"phone", order_by:"true", section:"contact", pretty_name: "Phone", data_type: "string"},
  ],
  team: [
    {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
    {name:"name",section:"basic",  pretty_name: "Name", data_type: "string", pretty_key:true},
    {name:"city",section:"basic",  pretty_name: "City", data_type: "string"},
    {name:"coach",section:"basic",  pretty_name: "Coach", references:"coach", crud_hide_column:true},
    {name:"arena",section:"basic",  pretty_name: "Arena", data_type: "string"},
    {name:"league",section:"placement",  pretty_name: "League", references:"league"},
    {name:"conference",section:"placement",  pretty_name: "Conference", references:"conference"},
    {name:"division",section:"placement",  pretty_name: "Division", references:"division"},
  ],
    prospect: [
      {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
          {name:"full_view", section:"basic", not_in_db:true,  restrict_from_view:true, pretty_name:"Full View", menu_link:"1"},
      {name:"image",section:"basic",  pretty_name: "Image", data_type: "image", crud_hide_column:true},
      {name:"first_name",section:"basic",  pretty_name: "First Name", data_type: "string"},
      {name:"last_name", order_by:"true", section:"basic", pretty_name: "Last Name", data_type: "string"},
      {name:"full_name", pretty_key:true, derived:"{first_name}  {last_name}",  section:"basic", pretty_name: "Full Name", data_type: "string",  order_by:false, crud_hide_column:true},
      {name:"nationality",section:"basic",  pretty_name: "Nationality", references:"nationality"},
      {name:"agent",section:"basic",  pretty_name: "Agent", references:"agent", crud_hide_column:true},
      {name:"date_of_birth",  section:"basic", pretty_name: "Date of Birth", data_type: "date", crud_hide_column:true, openToYearSelection:true},
      {name:"height",section:"basic",  pretty_name: "Height", data_type: "string", helper_text:"Feet/Inches", crud_hide_column:true},
      {name:"weight",section:"basic",  pretty_name: "Weight", data_type: "integer", helper_text:"Pounds", crud_hide_column:true},
  //    {name:"league",section:"basic",  pretty_name: "League", references:"league"},
      {name:"position", section:"player", pretty_name: "Position", data_type: "string"},
      {name:"player_number",  section:"player", pretty_name: "Number", data_type: "string"},
      {name:"college",section:"history",  pretty_name: "College", references:"college"},
      {name:"draft_year", section:"history",  pretty_name: "Draft Year",  data_type: "integer",  start_value:2000, end_value:2020, increment:1},
      {name:"team",section:"team",  pretty_name: "Team", references:"team"},
      {name:"team_city", section:"team", field_object_type:"team", field_field_name:"city"},

      {name:"reports",grid_col:12,  section:"reports", pretty_name:"Reports", referenced_by:"report"}
    ],
    report: [
      {name:"id", pretty_name: "Id", data_type: "integer", required:true, key:true},
      {name:"report", section:"basic", not_in_db:true,  restrict_from_view:true, pretty_name:"Full Report", menu_link:"2"},
      {name:"prospect",section:"basic",  pretty_name: "Prospect", references:"prospect", crud_hide_column:true},
      {name:"date_occurred",  section:"basic", pretty_name: "Date Occurred", data_type: "date", pretty_key:true},
      {name:"scout",section:"basic",  pretty_name: "Scout", references:"scout"},
      {name:"opponent",section:"basic",  pretty_name: "Opponent", references:"team"},
      {name:"report_type",section:"report",  pretty_name: "Report Type", references:"report_type"},
      {name:"main_report",section:"report",  pretty_name: "Main Report", data_type: "string", grid_col:12,  size:"large", crud_hide_column:true },
      {name:"setting",section:"report",  pretty_name: "Setting", data_type: "string"},
      {name:"nbaPosition",section:"report",  pretty_name: "NBA Position", data_type: "string"},
      {name:"bodyType",section:"report",  pretty_name: "Body Type", data_type: "string"},
      {name:"additionalNotes",section:"report",  pretty_name: "Additional Notes", data_type: "string",  grid_col:12,  size:"large", crud_hide_column:true},
      {name:"nbaComparison",section:"report",  pretty_name: "NBA Comparison", data_type: "string"},    
      {name:"roleCreator",section:"role", pretty_name:"Creator",  section:"role", data_type: "integer",grid_col:2, start_value:0, end_value:10, crud_hide_column:true},
      {name:"roleScorer", section:"role", pretty_name:"Scorer",  data_type: "integer", grid_col:2, start_value:0, end_value:10, crud_hide_column:true},
      {name:"roleShooter", section:"role", pretty_name:"Shooter",  data_type: "integer",grid_col:2,start_value:0, end_value:10, crud_hide_column:true},
      {name:"roleFinisher", section:"role", pretty_name:"Finisher",  data_type: "integer",grid_col:2, start_value:0, end_value:10, crud_hide_column:true},
      {name:"roleRebounder", section:"role", pretty_name:"Rebounder",  data_type: "integer", grid_col:2,start_value:0, end_value:10, crud_hide_column:true},
      {name:"roleDefender",section:"role",  pretty_name:"Defender",  data_type: "integer",  grid_col:2,start_value:1, end_value:10, crud_hide_column:true},
      {name:"roleRimProtector",section:"role",  pretty_name:"Rim Protector",   data_type: "integer", grid_col:2,  start_value:0, end_value:10, crud_hide_column:true},
    ],
}

export default metadata_fields
